package main

import (
	"context"
	"testing"
	"time"

	"github.com/video-site/backend/internal/catalog"
	"github.com/video-site/backend/internal/config"
)

func openServerTagMaintenanceCatalog(t *testing.T) (*catalog.Catalog, context.Context) {
	t.Helper()
	cat, err := catalog.Open(t.TempDir() + "/catalog.db")
	if err != nil {
		t.Fatalf("open catalog: %v", err)
	}
	t.Cleanup(func() {
		if err := cat.Close(); err != nil {
			t.Fatalf("close catalog: %v", err)
		}
	})
	return cat, context.Background()
}

func seedServerTagVideo(t *testing.T, cat *catalog.Catalog, id, title string) {
	t.Helper()
	now := time.Now()
	if err := cat.UpsertVideo(context.Background(), &catalog.Video{
		ID:          id,
		DriveID:     "drive",
		FileID:      "file-" + id,
		FileName:    id + ".mp4",
		Title:       title,
		PublishedAt: now,
		CreatedAt:   now,
		UpdatedAt:   now,
	}); err != nil {
		t.Fatalf("seed %s: %v", id, err)
	}
}

func mustListTagsForServer(t *testing.T, ctx context.Context, cat *catalog.Catalog) []catalog.Tag {
	t.Helper()
	tags, err := cat.ListTags(ctx)
	if err != nil {
		t.Fatalf("list tags: %v", err)
	}
	return tags
}

func TestCollectTagTitleClustersUsesRelaxedTitleSimilarity(t *testing.T) {
	videos := []*catalog.Video{
		{ID: "a", Title: "abcdefghijklmnopqrst"},
		{ID: "b", Title: "abcdefghijklmnopqXYZ"},
		{ID: "c", Title: "完全不同的内容"},
	}
	groups := collectTagTitleClusters(videos)
	if len(groups) != 1 || len(groups[0]) != 2 {
		t.Fatalf("groups = %#v, want one two-video cluster", groups)
	}
}

func TestTitleClusterPropagationUsesTwoVotesAndSkipsManualRecipient(t *testing.T) {
	cat, ctx := openServerTagMaintenanceCatalog(t)
	for _, id := range []string{"cluster-a", "cluster-b", "cluster-c", "cluster-manual"} {
		seedServerTagVideo(t, cat, id, "完全相同的系列标题")
	}
	for _, label := range []string{"cluster-tag", "locked-tag"} {
		if _, err := cat.EnsureTag(ctx, label, "user"); err != nil {
			t.Fatalf("ensure %s: %v", label, err)
		}
	}
	for _, id := range []string{"cluster-a", "cluster-b"} {
		if _, err := cat.AddVideoTagAssignments(ctx, id, []catalog.TagAssignment{{
			Label: "cluster-tag", Source: "auto", Evidence: "seed",
		}}); err != nil {
			t.Fatalf("seed tag %s: %v", id, err)
		}
	}
	if err := cat.SetManualVideoTags(ctx, "cluster-manual", []string{"locked-tag"}); err != nil {
		t.Fatalf("lock recipient: %v", err)
	}

	app := &App{cat: cat, cfg: &config.Config{}}
	added, err := app.propagateTagsAcrossTitleClusters(ctx)
	if err != nil {
		t.Fatalf("propagate title clusters: %v", err)
	}
	if added != 1 {
		t.Fatalf("added = %d, want cluster-tag on cluster-c only", added)
	}
	recipient, _ := cat.GetVideo(ctx, "cluster-c")
	if len(recipient.Tags) != 1 || recipient.Tags[0] != "cluster-tag" {
		t.Fatalf("recipient tags = %#v", recipient.Tags)
	}
	locked, _ := cat.GetVideo(ctx, "cluster-manual")
	if len(locked.Tags) != 1 || locked.Tags[0] != "locked-tag" {
		t.Fatalf("manual recipient changed: %#v", locked.Tags)
	}
	metadata, err := cat.ListVideoTagMetadata(ctx, []string{"cluster-c"})
	if err != nil {
		t.Fatalf("metadata: %v", err)
	}
	if got := metadata["cluster-c"]["cluster-tag"]; got.Source != "propagated" || got.Evidence != "标题聚类" {
		t.Fatalf("propagated metadata = %#v", got)
	}
}

func TestRunTagRetagWritesUpgradeMarkerOnlyAfterSuccess(t *testing.T) {
	cat, ctx := openServerTagMaintenanceCatalog(t)
	seedServerTagVideo(t, cat, "retag-video", "retag-keyword")
	if _, err := cat.EnsureTag(ctx, "retag-keyword", "user"); err != nil {
		t.Fatalf("ensure retag label: %v", err)
	}
	app := &App{cat: cat, cfg: &config.Config{}}
	if !app.beginTagJob("retag") {
		t.Fatal("begin retag job rejected")
	}
	app.runTagRetag(ctx, true)

	status := app.tagJobStatus()
	if status.State != "completed" || status.Running || status.Processed != 1 {
		t.Fatalf("status = %#v", status)
	}
	marker, err := cat.GetSetting(ctx, tagRetagUpgradeMarker, "")
	if err != nil || marker != "1" {
		t.Fatalf("marker = %q, %v", marker, err)
	}
	video, _ := cat.GetVideo(ctx, "retag-video")
	found := false
	for _, label := range video.Tags {
		if label == "retag-keyword" {
			found = true
		}
	}
	if !found {
		t.Fatalf("retagged labels = %#v", video.Tags)
	}
}

func TestRunTagRetagSkipsAutoMatchingWhenAutoGenerateDisabled(t *testing.T) {
	cat, ctx := openServerTagMaintenanceCatalog(t)
	seedServerTagVideo(t, cat, "disabled-retag-video", "disabled-keyword old-generated")
	if _, err := cat.EnsureTag(ctx, "disabled-keyword", "user"); err != nil {
		t.Fatalf("ensure user label: %v", err)
	}
	if _, err := cat.EnsureTag(ctx, "old-generated", "generated"); err != nil {
		t.Fatalf("ensure generated label: %v", err)
	}
	blocked, err := cat.EnsureTag(ctx, "blocked-generated", "generated")
	if err != nil {
		t.Fatalf("ensure blocked generated label: %v", err)
	}
	if _, err := cat.DeleteTag(ctx, blocked.ID); err != nil {
		t.Fatalf("delete blocked generated label: %v", err)
	}
	if _, err := cat.AddVideoTagAssignments(ctx, "disabled-retag-video", []catalog.TagAssignment{{
		Label: "old-generated", Source: "auto", Evidence: "old",
	}}); err != nil {
		t.Fatalf("seed old auto assignment: %v", err)
	}
	if err := cat.SetAutoGenerateTagsEnabled(ctx, false); err != nil {
		t.Fatalf("disable auto generate: %v", err)
	}

	app := &App{cat: cat, cfg: &config.Config{}}
	if !app.beginTagJob("retag") {
		t.Fatal("begin retag job rejected")
	}
	app.runTagRetag(ctx, false)

	status := app.tagJobStatus()
	if status.State != "completed" || status.Running || status.Processed != 1 {
		t.Fatalf("status = %#v", status)
	}
	video, err := cat.GetVideo(ctx, "disabled-retag-video")
	if err != nil {
		t.Fatalf("get video: %v", err)
	}
	if len(video.Tags) != 0 {
		t.Fatalf("auto-generated tags should be cleared without rematching: %#v", video.Tags)
	}
	for _, tag := range mustListTagsForServer(t, ctx, cat) {
		if tag.Label == "old-generated" {
			t.Fatalf("generated tag was not removed: %#v", tag)
		}
	}
	if err := cat.SetAutoGenerateTagsEnabled(ctx, true); err != nil {
		t.Fatalf("re-enable auto generate: %v", err)
	}
	if _, err := cat.EnsureTag(ctx, "blocked-generated", "generated"); err != nil {
		t.Fatalf("blocked-generated should be restorable after tombstone cleanup: %v", err)
	}
}

func TestPostStartupTagMaintenanceRunsBehindSharedJobState(t *testing.T) {
	cat, ctx := openServerTagMaintenanceCatalog(t)
	seedServerTagVideo(t, cat, "post-startup-video", "post-startup-keyword")
	for _, title := range []string{"FC2PPV-3259498", "FC2PPV-4162750", "FC2PPV-4768873"} {
		seedServerTagVideo(t, cat, "post-startup-"+title, title)
	}
	if _, err := cat.EnsureTag(ctx, "post-startup-keyword", "user"); err != nil {
		t.Fatalf("ensure label: %v", err)
	}
	if err := cat.SetSetting(ctx, tagRetagUpgradeMarker, "1"); err != nil {
		t.Fatalf("set completed upgrade marker: %v", err)
	}
	app := &App{cat: cat, cfg: &config.Config{}}
	if !app.beginTagJob("retag") {
		t.Fatal("begin post-startup job rejected")
	}
	app.runPostStartupTagMaintenance(ctx)

	status := app.tagJobStatus()
	if status.State != "completed" || status.Running || status.Processed != 4 || status.Total != 4 {
		t.Fatalf("status = %#v", status)
	}
	video, err := cat.GetVideo(ctx, "post-startup-video")
	if err != nil {
		t.Fatalf("get video: %v", err)
	}
	found := false
	for _, label := range video.Tags {
		if label == "post-startup-keyword" {
			found = true
		}
	}
	if !found {
		t.Fatalf("post-startup labels = %#v", video.Tags)
	}
	seriesVideo, err := cat.GetVideo(ctx, "post-startup-FC2PPV-3259498")
	if err != nil {
		t.Fatalf("get series candidate: %v", err)
	}
	for _, label := range seriesVideo.Tags {
		if label == "FC2PPV" {
			t.Fatalf("post-startup maintenance should not sync series tags: %#v", seriesVideo.Tags)
		}
	}
}

func TestStartPostStartupTagMaintenanceSkipsCompletedUpgrade(t *testing.T) {
	cat, ctx := openServerTagMaintenanceCatalog(t)
	seedServerTagVideo(t, cat, "post-startup-skip", "post-startup-skip-keyword")
	if _, err := cat.EnsureTag(ctx, "post-startup-skip-keyword", "user"); err != nil {
		t.Fatalf("ensure label: %v", err)
	}
	if err := cat.SetSetting(ctx, tagRetagUpgradeMarker, "1"); err != nil {
		t.Fatalf("set completed upgrade marker: %v", err)
	}
	app := &App{cat: cat, cfg: &config.Config{}}
	app.startPostStartupTagMaintenance(ctx)

	status := app.tagJobStatus()
	if status.State != "idle" || status.Running || status.Total != 0 || status.Processed != 0 {
		t.Fatalf("completed upgrade should not start post-startup tag job: %#v", status)
	}
	video, err := cat.GetVideo(ctx, "post-startup-skip")
	if err != nil {
		t.Fatalf("get video: %v", err)
	}
	if len(video.Tags) != 0 {
		t.Fatalf("completed upgrade restart should not classify tags: %#v", video.Tags)
	}
}
